### ISSUE TITLE
Continue to get Connection Refused Error at end of Set-up

### ISSUE THREAD

**Issue by MannyBPi** [kyleflan/tempiture#6]
On repeated attempts on a Raspberry Pi3B running Buster, complete the set-up but with the error curl: (7) Failed to connect to tempiture.local port 3000: Connection refused just before the end.

![Screen Shot 2020-06-25 at 12 06 46 AM](https://user-images.githubusercontent.com/67404181/85652201-01c15680-b678-11ea-931a-afdfb9cbeb14.png)

**Comment by kyleflan** [comment]
It looks like your docker containers aren't running. Can you show the output of:

`docker image ls`

You should see a few images listed. If not, part of the setup didn't work.

Try this, too, and send the output:

```bash
cd tempiture  # or whatever your tempiture folder is named
docker-compose -f ./docker/docker-compose.yml -p tempiture up
```

**Comment by MannyBPi** [comment]
It looks like docker is not installing at all.  Can see this a few lines up on the install and any docker command says command not found.
![15FFEEB3-9D3D-4947-9D52-8B1D90752FE0](https://user-images.githubusercontent.com/67404181/85790769-cc138080-b6fe-11ea-8cb0-cc404dd3753c.png)

**Comment by kyleflan** [comment]
I see now that you're on buster. This has only been tested on jessie. It doesn't look like there are docker-hypriot packages for buster (yet or at all). But it does seem that docker is available from the repo for buster.

Can you try installing docker and docker-compose from the repo? 

```bash
sudo apt-get update
sudo apt-get install docker.io docker-compose
```

If that doesn't work, take a look at this [thread ](https://github.com/docker/for-linux/issues/709)and see if some of the alternate solutions work. Supposedly this one-line works `curl -sL get.docker.com | sed 's/9)/10)/' | sh` but I would try the repo first.

Also, it looks like npm isn't installed. Check the output from setup.sh to look for errors about the npm install. (Or you can just install it manually)

Once you have docker and npm installed, you can comment out lines 8, 22-27 in the setup.sh and if all goes well, be up and running.

**Comment by MannyBPi** [comment]
Thanks for your help.  After fighting with docker for a while and getting nowhere, I decided to go my own way.  I started over and went with InfluxDB and Grafana.  I will probably comeback and retry what you have here with a fresh Stretch install and see if that works.
